// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkgOERNgQ4SxBqVDeDYaTYZSmuZW9fwzI',
    appId: '1:190921651209:web:222859465905af0f61b4d8',
    messagingSenderId: '190921651209',
    projectId: 'fir-series-8d072',
    authDomain: 'fir-series-8d072.firebaseapp.com',
    storageBucket: 'fir-series-8d072.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCso7IBMMFJz0eBd3nfBJ5lEhsxf-t2iSU',
    appId: '1:190921651209:android:31cdae8d0efe6f9461b4d8',
    messagingSenderId: '190921651209',
    projectId: 'fir-series-8d072',
    storageBucket: 'fir-series-8d072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cr-f__16x2jN1CLPWHbdkTrv7iwGcBs',
    appId: '1:190921651209:ios:bc495f7701fd2e7761b4d8',
    messagingSenderId: '190921651209',
    projectId: 'fir-series-8d072',
    storageBucket: 'fir-series-8d072.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
